spring.application.name=delivery-service

server.port=8085

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
jwt.secret=${JWT_SECRET}

foodflow.internal-api-key=${FOODFLOW_INTERNAL_API_KEY}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Consumer
spring.kafka.consumer.group-id=delivery-service
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.foodflow.common.Event

# ==============================
# User Service - Circuit Breaker
# ==============================

resilience4j.circuitbreaker.instances.userService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.userService.register-health-indicator=true

# ==============================
# User Service - Retry
# ==============================

resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms
resilience4j.retry.instances.userService.enable-exponential-backoff=true
resilience4j.retry.instances.userService.exponential-backoff-multiplier=2

# ==============================
# Feign Timeout
# ==============================

spring.cloud.openfeign.client.config.user-service.connect-timeout=2000
spring.cloud.openfeign.client.config.user-service.read-timeout=3000

# ==============================
# Actuator
# ==============================

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics