package com.foodflow.common.Event;

public enum EventType {
    ORDER_CREATED,
    ORDER_CONFIRMED,
    ORDER_ACCEPTED,
    FOOD_READY,

    PAYMENT_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    INVENTORY_RESERVED,
    INVENTORY_RESERVATION_FAILED,
    INVENTORY_RELEASED,

    PARTNER_AVAILABLE,
    PARTNER_BUSY,

    DELIVERY_ASSIGNED,
    OUT_FOR_DELIVERY,
    DELIVERED
}
